spring:
  thymeleaf:
    mode: HTML
    cache: false
    encoding: utf-8
  profiles:
    active: dev
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

comment.avatar: /images/zhutou.jpg


